rtsp_url: rtsp://admin:dcba123654@192.168.102.15:554/Stream/Channels/101?resolution=1920x1080
resize_width: 1920
resize_height: 1080
auto_connect_camera: true
rtsp_transport: udp
rtsp_auto_switch: true
buffer_size: 10
connection_timeout: 10.0
frame_timeout: 3.0
enable_frame_interpolation: false
adaptive_quality: true
object_threshold: 1.0
alert_cooldown: 20
telegram_bot_token: xxxxxxxxxxxxxxxxxO0RYx8ACnLnTiJU7k2wx8ZAw
telegram_chat_id: '-1002495575128'
telegram_message_thread_id: 2
yolo_model_path: yolo11n.pt
use_gpu: true
yolo_confidence_threshold: 0.25
detection_input_size:
- 640
- 640
enable_half_precision: true
classes_of_interest:
- 0
- 1
- 2
- 3
- 4
- 5
- 6
- 7
- 8
- 9
- 10
- 11
- 12
- 13
- 14
- 15
- 16
- 17
- 18
- 19
- 20
- 21
- 22
- 23
- 24
- 25
- 26
- 27
- 28
- 29
- 30
- 31
- 32
- 33
- 34
- 35
- 36
- 37
- 38
- 39
- 40
- 41
- 42
- 43
- 44
- 45
- 46
- 47
- 48
- 49
- 50
- 51
- 52
- 53
- 54
- 55
- 56
- 57
- 58
- 59
- 60
- 61
- 62
- 63
- 64
- 65
- 66
- 67
- 68
- 69
- 70
- 71
- 72
- 73
- 74
- 75
- 76
- 77
- 78
- 79
enable_sound_alert: false
sound_alert_file: alert_sound.mp3
email_enabled: false
email_smtp_server: smtp.gmail.com
email_smtp_port: 587
email_use_ssl: true
email_username: ''
email_password: ''
email_from: ''
email_to: ''
